### ISSUE TITLE
Any idea about using example in swagger file while not generating random records?

### ISSUE THREAD

**Issue by rapax87** [muonsoft/openapi-mock#15]
Hi there,

Any idea about using example request and response in swagger file while not generating random records?

**Comment by nirdosh17** [comment]
Facing same issue.

**Comment by strider2038** [comment]
Ok, I will add this feature to the plan. I will return to work on project in october.

**Comment by rapax87** [comment]
And I think it will be a great feature if mock server use examples of swagger file and give the corresponding response to a request with the same example name.
For now, I didn't see anyone did it. It is a little bit complicated but it will be very cool.

**Comment by rafaltrojanowski** [comment]
Hi,

I'm going to use `swagger-mock`, is there any update on this issue? :)

**Comment by strider2038** [comment]
I'm sorry, I can not make any promises about the project. We are planning to rewrite it in Go and use a separate library for parsing OpenAPI specification, but it will not be soon.

**Comment by rafaltrojanowski** [comment]
Thanks and good luck with rewriting it in Go!

**Comment by strider2038** [comment]
This feature was added in version [v0.2](https://github.com/muonsoft/openapi-mock/releases/tag/v0.2.0). Be aware, project was moved to another location. Please, read [project description](https://github.com/muonsoft/openapi-mock/blob/master/README.md) for more information.
