### ISSUE TITLE
Options to control generation process Environment Variables in docker-composer not work

### ISSUE THREAD

**Issue by gring2** [muonsoft/openapi-mock#48]
swagger file: person.yaml example file

I have environment variables.
      SWAGGER_MOCK_DEFAULT_MIN_FLOAT: 10.0
      SWAGGER_MOCK_DEFAULT_MAX_FLOAT: 100.0
      SWAGGER_MOCK_DEFAULT_MAX_INT: 10
      SWAGGER_MOCK_DEFAULT_MIN_INT: 8
      SWAGGER_MOCK_USE_EXAMPLES: 'exclusively'

how ever server still generate random values.

**Comment by strider2038** [comment]
Hello, @gring2! Thank you for the report!

There were some mistakes in docs: all options start with `OPENAPI_MOCK` prefix, not `SWAGGER_MOCK`.

Fixed version of docs <https://github.com/muonsoft/openapi-mock/blob/master/docs/usage_guide.md>.
