### ISSUE TITLE
Mockserver UI not available

### ISSUE THREAD

**Issue by alx-kpk** [muonsoft/openapi-mock#64]
[Mockserver UI](https://www.mock-server.com/mock_server/mockserver_ui.html) can not be reached over http://localhost:8080/mockserver/dashboard

**Comment by strider2038** [comment]
@alx-kpk, this is another project. Suppose, you are talking about this project https://github.com/mock-server/mockserver.

**Comment by alx-kpk** [comment]
Ah, thanks for the hint. I thought this is a fork of the other project.
