### ISSUE TITLE
Doc: Specified the operation of the parameter specification_url

### ISSUE THREAD

**Issue by T1p0un3t** [muonsoft/openapi-mock#74]
Hello,

The documentation for this setting lacks information on how it works.

It should be specified that a relative path must be relative to the configuration file (forced in the [automatic correction](https://github.com/muonsoft/openapi-mock/blob/master/internal/application/config/Load.go#L72) of configuration values).

**Comment by strider2038** [comment]
Added examples and description to the docs https://github.com/muonsoft/openapi-mock/blob/master/docs/usage_guide.md#specification_url

**Comment by T1p0un3t** [comment]
thank you !
